### ISSUE TITLE
Refactor equivalence classes construction

### ISSUE THREAD

**Issue by jccriado** [jccriado/matchingtools#16]
- The first line of `Match._map_tensors` does a trick that should be only temporary. The grouping of tensors of some `Operator` instance by forgetting their indices could a responsibility of that operator. A method `Operator.group_tensors` would eliminate the need for the first line of `Match._map_tensors`, make the construction of `pattern_eqclasses` straightforward and would not reintroduce any circular dependencies.

- The construction of `associates` in `Match._map_tensors` can be left as it is or be made more symmetric, by using the proposed `Operator.group_tensors`. Then a (bijective) mapping should be constructed only between the representatives on each side. `associates` is easily built from this. I do not think, however, that this approach has any advantages, apart from perhaps a bit more of clarity.

**Comment by namasme** [comment]
The hack could probably be solved, or at least improved (e.g. `tensors_do_match = pattern_operator.tensors[0].__class__.does_match`). I think the bottom line here is whether we can effectively move this behaviour to `Operator` in order to cache the result of computing `pattern_eqclasses` for future reference (useful for `Rule`s). However, this introduces a big dependency on the immutability of the operator tensors (even if `Operator.tensors` was a tuple instead of a list it should be impossible to write to that attribute). Even though I think we're doing a good work about immutability and such, this is not enforced by our current stack at any level and might become a pain down the road, so we must be careful with these kinds of optimizations (which will surely appear again soon enough).

As for the actual building of the equivalence classes of the target, I agree it would be more appealing but I don't really think it would represent a boost in performance but rather a hindrance. `Rule` patterns will probably be matched (succeeding or not) against different targets much more frequently than the other way around (if only because there will usually be more targets than patterns), and the classes will probably be very sparse too.

**Comment by jccriado** [comment]
I agree on the point about the building of equivalence classes of the target.

About the hack: what worries me about `tensors[0].__class__.does_match` and similar code is that it is sensible to changes in the tensors classes. If at some point there's a tensor class that implements its own `does_match` this is going to break.

Are there any reasons not to move `does_match` back to `Match` (ensuring that it won't change from tensor to tensor)? If there aren't any, this would be a satisfactory solution for me.

**Comment by jccriado** [comment]
`tensors_do_match` is now a method of `Match`, but there's the problem that for different types of tensors it should check equality over different attributes. This can be solved by adding a member `matching_attributes` (or similar) to tensors. It can be implemented as a dictionary `{attribute: value}`. (Can/should we use a named tuple for this?)

**Comment by namasme** [comment]
The problem with `namedtuple` is that the attribute names are just sugar because internally the data is represented as a `tuple` (which makes sense if you come to think it inherits from `tuple` and is named `namedtuple`). So, things like this happen:

```
Foo = namedtuple('Foo', ['x', 'y'])
Bar = namedtuple('Bar', ['y', 'x'])
Baz = namedtuple('Bar', ['z', 'z2'])


Foo(1, 2) == Bar(1, 2)
Foo(1, 2) == Baz(1, 2)
Bar(1, 2) == Baz(1, 2)
```

This means that, even if we fixed a certain order in the common attributes (e.g. name, indices, dimension), two such objects with the same number of attributes which, by lucky coincidence, would agree on all their values (sequentially), would spuriously be considered equal.

My understanding is that this does not suit our needs, so I'm sticking with the `dict` solution.

**Comment by jccriado** [comment]
I agree on using the `dict` solution, then.

**Comment by jccriado** [comment]
15c20466bb8a9599d427bc824be9b367306b8806 finally solves this issue
